services:
  - type: web
    name: sklad-accounting
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse-db
          property: connectionString
  - type: postgresql
    name: warehouse-db
    plan: free
    ipAllowList: []
